hasker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from qa_app import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('api/v1/', include('qa_rest_api_v1.urls')),
    path('user/', include('user_profile.urls'), name='user_profile'),
    path('qa/', include(('qa_app.urls', 'qa_app'), namespace='qa')),
    path('', views.IndexListView.as_view(), name='index'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa_app/urls.py
from django.urls import path

from qa_app import views


urlpatterns = [
    path('hot', views.IndexListView.as_view(), name='hot'),
    path('search', views.SearchListView.as_view(), name='search'),
    path('accounts/myquestions/', views.MyQuestionsListView.as_view(), name='myquestions'),
    path('accounts/myanswers/', views.MyAnswersListView.as_view(), name='myanswers'),
    path('question/new', views.QuestionCreateView.as_view(), name='new_question'),
    path('question/<int:pk>', views.QuestionCreateAnswerView.as_view(), name='question'),
    path('tag/<int:pk>', views.TagDetailView.as_view(), name='tag'),
    path('right_answer/<int:pk>', views.RightAnswerActionView.as_view(), name='right_answer'),
    path('vote/<str:model_entity>/<int:pk>/<str:value_alias>', views.VoteActionView.as_view(), name='vote'),
]

qa_app/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models import Count, Q, Sum
from django.template.defaultfilters import truncatechars
from django.shortcuts import reverse

from hasker.settings import AUTH_USER_MODEL
from user_profile.models import User


class Tag(models.Model):
    name = models.CharField(verbose_name='Тег', max_length=64, blank=False)

    def __str__(self):
        return self.name


class Question(models.Model):
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    title = models.CharField(verbose_name='Заголовок вопроса', max_length=256, blank=False)
    content = models.TextField(verbose_name='Текст вопроса', max_length=16384, blank=False)
    author = models.ForeignKey(AUTH_USER_MODEL, related_name='questions', on_delete=models.CASCADE, blank=False)
    tags = models.ManyToManyField(Tag, related_name='questions', blank=True)

    class Meta:
        ordering = ['-id']

    # TODO: change to cashed BooleanField
    @property
    def has_answer(self):
        return bool(self.answers.filter(is_right=True))

    @property
    def votes_sum(self):
        votes = self.votes.aggregate(Sum('value'))
        return votes['value__sum'] if votes['value__sum'] else 0

    def get_sorted_answers(self):
        return self.answers.annotate(sum_votes=Sum('votes__value')).order_by('-is_right', '-sum_votes', 'created_at')

    @staticmethod
    def get_last():
        return Question.objects.annotate(count_answers=Count('answers')).order_by('-created_at', '-id')

    @staticmethod
    def get_hot():
        return Question.objects.annotate(count_answers=Count('answers')).order_by('-count_answers', '-id')

    @staticmethod
    def get_trending():
        return Question.objects.annotate(count_votes=Count('votes')).order_by('-count_votes', '-id')

    @staticmethod
    def search(text):
        return Question.objects.filter(Q(title__icontains=text) | Q(content__icontains=text))\
            .annotate(count_answers=Count('answers')).order_by('-id')

    @staticmethod
    def get_by_tag(tag_name):
        try:
            return Tag.objects.get(name__iexact=tag_name).questions.all().order_by('-id')
        except Tag.DoesNotExist:
            return Question.objects.none()

    @staticmethod
    def get_by_user(user):
        return Question.objects.filter(author=user).annotate(count_answers=Count('answers')).order_by('-created_at')

    def get_tags(self):
        return self.tags.all()

    def get_absolute_url(self):
        return reverse('qa:question', kwargs={'pk': self.pk})

    def __str__(self):
        return truncatechars(self.title, 64)


class Answer(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Question, related_name='answers', on_delete=models.CASCADE)
    content = models.TextField(max_length=16384, blank=False)
    author = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False)
    is_right = models.BooleanField(verbose_name='Правильный ответ', default=False)

    class Meta:
        ordering = ['-id']

    @property
    def content_short(self):
        return truncatechars(self.content, 64)

    @property
    def votes_sum(self):
        votes_sum = self.votes.aggregate(Sum('value'))['value__sum']
        return votes_sum if votes_sum else 0

    @staticmethod
    def get_by_user(user):
        return Answer.objects.filter(author=user).order_by('-created_at')

    def __str__(self):
        return self.content_short


class Vote(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    value = models.SmallIntegerField(verbose_name='Оценка')
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='votes')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True, null=True, related_name='votes')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, blank=True, null=True, related_name='votes')

    def __str__(self):
        return "{} voted {}".format(self.user.username, self.value)

    @staticmethod
    def vote(model_object, user, value):
        object_name = 'question' if type(model_object) is Question else 'answer'
        try:
            vote = Vote.objects.get(**{object_name: model_object}, user=user)
            vote.value = value
            vote.save()
        except ObjectDoesNotExist:
            Vote.objects.create(**{object_name: model_object}, user=user, value=value)

    class Meta:
        unique_together = (('user', 'question'), ('user', 'answer'))

qa_app/forms.py
from django import forms
from django.core.exceptions import ValidationError

from hasker.settings import MAX_TAGS
from qa_app.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'content', 'tags']

    def clean_tags(self):
        data = self.cleaned_data['tags']
        if data.count() > MAX_TAGS:
            raise ValidationError('Maximum 3 tags')
        return data


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content', 'question']
        widgets = {'question': forms.HiddenInput, }


class SearchForm(forms.Form):
    search = forms.CharField()

qa_app/views.py
from django import views
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponseNotFound, HttpResponseForbidden, HttpResponseNotAllowed
from django.views.generic import CreateView, DetailView, ListView
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
import logging

from qa_app.forms import QuestionForm, AnswerForm
from qa_app.models import Question, Answer, Tag, Vote


logger = logging.getLogger('hasker.qa_app')


class IndexListView(ListView):
    model = Question
    template_name = 'index.html'
    context_object_name = 'last_questions'
    paginate_by = 10

    def get_queryset(self):
        if self.request.path == reverse('qa:hot'):
            return Question.get_hot()
        return Question.get_last()


class SearchListView(ListView):
    model = Question
    template_name = 'search.html'
    context_object_name = 'found_questions'
    paginate_by = 20

    def get_queryset(self):
        text = str(self.request.GET.get('q')).strip()
        if text.lower().startswith('tag:'):
            tag_name = text[4:].strip()
            try:
                return Question.get_by_tag(tag_name)
            except ObjectDoesNotExist:
                return Question.objects.none()
        return Question.search(text)


class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    form_class = QuestionForm
    login_url = 'login'

    template_name = 'question_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('qa:question', kwargs={'pk': self.object.pk})


class QuestionCreateAnswerView(CreateView):
    model = Answer
    form_class = AnswerForm
    template_name = 'question.html'

    def send_notification(self):
        email_subject = 'New answer from {}'.format(self.object.author)
        email_message = 'You have a new answer from {} on "{}":\r\n' \
                        '\r\n' \
                        '{}\r\n' \
                        '\r\n' \
                        '{}'.format(self.object.author,
                                    self.object.question.title,
                                    self.object.content,
                                    self.request.build_absolute_uri())
        try:
            send_mail(email_subject,
                      email_message,
                      'ivan@urlix.ru',
                      [self.object.question.author.email],
                      fail_silently=False)
        except Exception as e:
            # for Heroku deployment, change to external service in the future
            logger.debug("We've got an error during send mail via gmail: {}".format(e))

    def form_valid(self, form):
        self.success_url = self.request.path
        form.instance.author = self.request.user
        form_valid_result = super().form_valid(form)
        if form_valid_result and self.object.author.email:
            self.send_notification()
        return form_valid_result

    def get_context_data(self, **kwargs):
        self.initial = {'question': self.kwargs['pk']}
        context = super().get_context_data(**kwargs)
        question = get_object_or_404(Question, pk=self.kwargs['pk'])
        answers = question.get_sorted_answers()
        paginator = Paginator(answers, settings.ANSWERS_PER_PAGE)
        try:
            answers = paginator.get_page(self.request.GET.get('page'))
        except (PageNotAnInteger, KeyError) as e:
            answers = paginator.get_page(1)
        except EmptyPage:
            answers = paginator.get_page(paginator.num_pages)

        context.update({
            'question': question,
            'answers': answers,
            'paginator': paginator,
            'page_obj': answers,
        })
        return context
    #
    # def detail(request, id):
    #     context = dict()
    #     return render(request, 'question.html', context)


class TagDetailView(DetailView):
    model = Tag
    template_name = 'tag.html'


class RightAnswerActionView(LoginRequiredMixin, views.View):
    login_url = 'login'

    def get(self, request, pk):
        try:
            answer = get_object_or_404(Answer, pk=pk)
            if answer.question.author == request.user or request.user.is_superuser:
                # and not answer.question.answers.filter(is_right=True) :
                answer.question.answers.filter(is_right=True).update(is_right=False)
                answer.is_right = True
                answer.save()
                return redirect(answer.question)
            raise PermissionDenied('Incorrect user')
        except PermissionDenied:
            return HttpResponseForbidden('You DO NOT have an access')
        except Exception as e:
            logger.debug('Incorrect request: {}'.format(e))
            return HttpResponseNotAllowed('Incorrect request')


class VoteActionView(LoginRequiredMixin, views.View):
    login_url = 'login'

# TODO: refactor vote design
    def get(self, request, model_entity, pk, value_alias):
        if type(pk) is int \
           and type(model_entity) is str and model_entity in ('question', 'answer') \
           and type(value_alias) is str and value_alias in ('like', 'dislike'):
            try:
                value = 1 if value_alias == 'like' else -1
                if model_entity == 'answer':
                    answer = get_object_or_404(Answer, pk=pk)
                    question = answer.question
                    Vote.vote(answer, request.user, value)
                if model_entity == 'question':
                    question = get_object_or_404(Question, pk=pk)
                    Vote.vote(question, request.user, value)
                return redirect(question)
            except ObjectDoesNotExist as e:
                logger.debug("We've got an error during voting process: {}".format(e))

        return HttpResponseNotFound('Incorrect request')


class MyQuestionsListView(ListView):
    model = Question
    paginate_by = 10
    template_name = 'myquestions.html'

    def get_queryset(self):
        return Question.get_by_user(self.request.user)


class MyAnswersListView(ListView):
    model = Answer
    paginate_by = 10
    template_name = 'myanswers.html'

    def get_queryset(self):
        return Answer.get_by_user(self.request.user)

qa_app/templates/includes/answer.html
{% load vote %}
<div class="container">
    <div class="row">
        <div class="col-sm-2 text-center">

            {% vote answer %}

            {% if answer.is_right %}
                <span class="badge badge-success">Right!</span>
            {% elif user == question.author or user.is_superuser  %}
                <a class="btn btn-outline-success" href="{% url 'qa:right_answer' answer.pk %}" role="button">Right?</a>
            {% endif %}

        </div>
        <div class="col-sm">

            <p>{{ answer.content }}</p>

            <div class="text-right">
                <small class="text-black-50">answered {{ answer.created_at|timesince }} ago
                    <a href="#">{{ answer.author }}</a></small>
                {% include 'includes/avatar.html' with avatar=answer.author.avatar width="40" height="40" %}
            </div>

        </div>
    </div>
</div>
<hr class="my-1">

qa_app/templates/includes/answer_short.html
<div class="container p-0">
    <div class="row">
        <div class="col-sm-1">
            {% include 'includes/avatar.html' with avatar=answer.question.author.avatar width="60" height="60" %}
        </div>
        <div class="col-sm-11 p-0 pr-3">
            <a href="{% url 'qa:question' answer.question_id %}">{{ answer.question.title|truncatechars:128 }}</a><br/>
            <small class="text-black-50">Asked {{ answer.question.created_at|timesince }} ago</small>
            <br />
            <p class="{% if answer.is_right %}bg-success text-white border-success {% endif %}p-2 border">{{ answer.content|truncatechars:255 }}<br/>
            <small class="text-black-50">Answered {{ answer.created_at|timesince }} ago</small>
            </p>

        </div>
    </div>
</div>
<hr class="my-1">

qa_app/templates/includes/avatar.html
{% load thumbnail %}
{% load static %}

{% thumbnail avatar width|add:"x"|add:height crop="center" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-thumbnail">
{% empty %}
    <img src="{% static 'images/default.png' %}" width="{{ width }}" height="{{ height }}" class="img-thumbnail"/>
{% endthumbnail %}

qa_app/templates/includes/paginator.html
{% if paginator.num_pages > 1 %}
    <nav>
        <ul class="pagination">
        {% for page_num in paginator.page_range %}
            <li class="page-item{% if page_obj.number == page_num %} active{% endif %}">
                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% endfor %}
        </ul>
    </nav>
{% endif %}

qa_app/templates/includes/question_short.html
<div class="container p-0">
    <div class="row">
        <div class="col-sm-3">
            {% include 'includes/avatar.html' with avatar=question.author.avatar width="60" height="60" %}

            <span class="badge badge-success p-2 bg-white border text-success">
                {{ question.votes_sum }}<br />
                <small>votes</small>
            </span>
            <span class="badge badge-success p-2 border {% if question.has_answer %}text-white{% else %}bg-white text-success{% endif %}">
                {{ question.count_answers }}<br />
                <small>answers</small>
            </span>

        </div>
        <div class="col-sm-9 p-0 pr-3">
            <a href="{% url 'qa:question' question.id %}">{{ question.title|truncatechars:128 }}</a>
            <br />
            {% for tag in question.get_tags %}
                <span class="badge badge-secondary">{{ tag.name }}</span>
            {% endfor %}
            <br />

            <div class="text-right">
                <small class="text-black-50">Asked {{ question.created_at|timesince }} ago
                    <a href="#">{{ question.author }}</a></small>
            </div>
        </div>
    </div>
</div>
<hr class="my-1">

qa_app/templates/includes/trending_questions.html
<div class="container">
    <h4 class="text-center">Trending</h4>
    {% for question in trending_questions %}
    <div class="row py-1">
        <span class="badge badge-success p-2 bg-white border text-success mr-2">
            {{ question.votes_sum }}<br />
            <small>votes</small>
        </span>
        <a href="{% url 'qa:question' question.id %}">{{ question.title|truncatechars:24 }}</a>
    </div>
    {% endfor %}
</div>

qa_app/templates/includes/vote_widget.html
    <a href="{% url 'qa:vote' model_entity=model pk=pk value_alias='like' %}">Like!</a>
    {{ votes_sum }}
    <a href="{% url 'qa:vote' model_entity=model pk=pk value_alias='dislike' %}">Dislike!</a>