hasker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from qa_app import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('api/v1/', include('qa_rest_api_v1.urls')),
    path('user/', include('user_profile.urls'), name='user_profile'),
    path('qa/', include(('qa_app.urls', 'qa_app'), namespace='qa')),
    path('', views.IndexListView.as_view(), name='index'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa_app/urls.py
from django.urls import path

from qa_app import views


urlpatterns = [
    path('hot', views.IndexListView.as_view(), name='hot'),
    path('search', views.SearchListView.as_view(), name='search'),
    path('accounts/myquestions/', views.MyQuestionsListView.as_view(), name='myquestions'),
    path('accounts/myanswers/', views.MyAnswersListView.as_view(), name='myanswers'),
    path('question/new', views.QuestionCreateView.as_view(), name='new_question'),
    path('question/<int:pk>', views.QuestionCreateAnswerView.as_view(), name='question'),
    path('tag/<int:pk>', views.TagDetailView.as_view(), name='tag'),
    path('right_answer/<int:pk>', views.RightAnswerActionView.as_view(), name='right_answer'),
    path('vote/<str:model_entity>/<int:pk>/<str:value_alias>', views.VoteActionView.as_view(), name='vote'),
]

templates/account_menu.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <h1 class="display-4">Profile</h1>

    <a href="{% url 'profile' %}">Profile</a><br/>
    <a href="{% url 'qa:myquestions' %}">My Questions</a><br/>
    <a href="{% url 'qa:myanswers' %}">My Answers</a><br/>


{%  endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>{% block title %}Poor man's stackoverflow{% endblock title %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>

<div class="container">

    <div class="row">
        <div class="col-sm-12 pb-2">

            <nav class="navbar navbar-expand-sm navbar-light bg-light">
                <a class="navbar-brand" href="{% url 'index' %}">Haster</a>
                <div class="collapse navbar-collapse" id="collapsibleNavId">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

                    {% if user.is_authenticated %}
                        <li class="nav-item">
                        {% include 'includes/avatar.html' with avatar=user.avatar width="36" height="36" %}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account' %}">{{ user.get_username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>

                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registration' %}">Registration</a>
                        </li>
                    {% endif %}

                        <li class="nav-item">
                            <a class="nav-link" href="#rules">Rules</a>
                        </li>

                    </ul>
                    <form action="{% url 'qa:search' %}" class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="text" name="q"  placeholder="Search" value="{{ request.GET.q }}">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>

                </div>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-9 pt-3 pb-5">

            {% block content %}
            {% endblock %}

        </div>
        <div class="col-sm-3 p-3">
            <div class="container text-center my-5">
                <a class="btn btn-primary" href="{% url 'qa:new_question' %}" role="button">Ask Question!</a>
            </div>
            {% load trending_questions %}
            {% get_trending_questions %}

        </div>
    </div> <!-- endrow -->


    <div class="row">
        <div class="col-sm-12 bg-light py-3 m-3 text-center">
            Hasker &copy; 2019 <a href="{% url 'api_index' %}">API</a>
        </div>
    </div>
</div>

</body>
</html>